### ISSUE TITLE
Remove PlainPost and rename ZeroBin

### ISSUE THREAD

**Issue by irdan** [privly/privly-applications#110]
Giving users a choice between PlainPost and ZeroBin serves as a point of confusion.  PlainPost and ZeroBin do not differ significantly from the perspective of users.  We should remove PlainPost, and rename ZeroBin to message.

This eliminates confusion about ZeroBin being a separate peice of software from Privly, and makes the right choice for users by default.  Of course, documentation and threat models will make reference to ZeroBin, but general users should not be exposed this level of detail.

This will simplify rollout initially, and additional applications can be added over time with meaningful-to-user application names.

**Comment by smcgregor** [comment]
This is done.
