### ISSUE TITLE
Options page nav bar incorrectly shows log out

### ISSUE THREAD

**Issue by kbaileyky** [privly/privly-applications#148]
Moved from https://github.com/privly/privly-chrome/issues/82.

When not logged into to Privly, if the Options page is selected from the drop down menu, the user will be taken to the options page as though they have already logged in. The log out option should be log in.

![image](https://cloud.githubusercontent.com/assets/2293747/6115511/dabed4d2-b05a-11e4-9bde-21b2002b28f9.png)

This happened on a computer that never logged in privly before.

**Comment by smcgregor** [comment]
What happens when you click "logout" and return to this page?

**Comment by kbaileyky** [comment]
The page looks the same, as if I had logged in.

**Comment by smcgregor** [comment]
I suspect there is an error in the JavaScript console, could you report if
there are any problems there? I can give instructions on finding the
console when I am back at my laptop.

**Comment by kbaileyky** [comment]
I can, but I would need instructions, I am still learning javascript. 

Also, when was 0.4.0. released? I can't find the date. I just realized since I am running privly on a school computer that it is very likely it is not the most up to date code.

**Comment by smcgregor** [comment]
It was a few months ago so I suspect this is why I am not seeing the same behavior. I'll publish an update the Chrome store and you can either comment again or close the issue.

**Comment by kbaileyky** [comment]
Yes, the version on the computer was old. Sorry!
