### ISSUE TITLE
Fix wrapping on History app

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-applications#151]
On small (mobile) screens the History app's contents overflow.

To fit within the confines of the mobile screen we need to shrink the buttons on the left and allow the text to wrap within the cells.

You can replicate this issue on the web browser by shrinking the width of the window to be very small.

See a screen capture and the cross-references issue: https://github.com/privly/privly-android/issues/33

**Comment by vshivam** [comment]
This is what it looks like on the phone. 
![screenshot_2015-03-01-22-53-04](https://cloud.githubusercontent.com/assets/831071/6431306/7b2b7dec-c066-11e4-94ef-a941aad075e0.png)
