### ISSUE TITLE
Logged out navigation. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-applications#154]
Since, the login is handled on the Java side on the android platform, it might be better to redirect the user to the the login provided by the app when the auth token validation fails rather than the html login page. 

We could probably add it here : https://github.com/privly/privly-applications/blob/master/shared/javascripts/network_service.js#L439

**Comment by smcgregor** [comment]
How do you want the JS webview to notify the Java code? Call a specific function (define it for me), fire an event, another option?

**Comment by vshivam** [comment]
Yeah, I can define a method in the JS Bridge which'll redirect the user to the Login Activity.

**Comment by smcgregor** [comment]
If you get me a snippet or open a pull request, I'll take care of it.

**Comment by vshivam** [comment]
Fixed in currently pending pull request : https://github.com/privly/privly-applications/pull/218
