### ISSUE TITLE
Improve Login/Registration Page

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-applications#163]
This is intended to be an introductory issue for people new to Privly development since it requires HTML/CSS knowledge and a working development environment.

A screen capture of the current login page is below. Your task is to _make it better_. Generally it is bad form to do things like present a login form and a registration form with minimal help and differentiation. Usually you want to default to the login form with a link to open the registration form.

![screen shot 2015-02-24 at 7 24 39 pm](https://cloud.githubusercontent.com/assets/64780/6364443/d13ea26e-bc5a-11e4-8237-82f8e987fb29.png)

**Comment by hitesh96db** [comment]
This looks like something I could get started with, btw out of curiosity, are the icons meant to be on the right-side of the text ? - that's a bit strange, since most of the web-apps have icons to the left.

**Comment by smcgregor** [comment]
If they look better on the left, please open a separate pull request and we'll see if other devs/users agree. I don't have a strong opinion at this point since I really need to see it.

**Comment by katten-kits** [comment]
I've been messing around with the Login application for a few days myself. :) So far, I've put the registration form into a bootstrap modal, which may help with differentiation. Would that be a good solution to this problem?

**Comment by hitesh96db** [comment]
Oh you have ? I guess I'll leave this then.

**Comment by smcgregor** [comment]
@katten-kits Sounds like a good approach.

@hitesh96db I believe you are working on something else at this point, but it is OK for multiple people to be working on the same problem. The final approach can often combine the best aspects of independent lines of development.

**Comment by smcgregor** [comment]
Several changes have been made so this issue is no longer valid. I will open new "introductory" issues in a few weeks to replace this one.
