### ISSUE TITLE
Remove Warning of Deletion from Footer

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-applications#164]
By default all content is destroyed within 30 days, but users may now opt to have their encrypted content stored forever(?). This means we should remove the warning "This post is temporary. All new content is destroyed within 30 days"

This issue is intended to be a good introductory issue for learning the Priv.ly Project's build system.

![screen shot 2015-02-27 at 4 19 43 pm](https://cloud.githubusercontent.com/assets/64780/6423539/7b74a736-be9c-11e4-8880-2355922aedac.png)

**Comment by sammyshj** [comment]
@smcgregor I cannot replicate this bug on my system. I think this issue has already been resolved. Please look into it and close the issue.

**Comment by smcgregor** [comment]
Perhaps I was on an older branch at the time. Sorry for the wild goose
chase. I'll confirm then close.

**Comment by smcgregor** [comment]
Confirmed via grep.
