### ISSUE TITLE
Change Posting Prompts to be a Clearer Step by Step

### ISSUE THREAD

**Issue by spectralsun** [privly/privly-applications#166]
When you are posting a new link without originating it from the context menu (right click) or the posting button, you see a series of messages that tell you what to do. This is essentially a step-by-step guide, but it is currently displayed as a series of boxes that appear after clicking in the proper place. The step-by-step nature of this process could be made more explicit by perhaps adding numbers to the left hand side of the popup.

**Comment by smcgregor** [comment]
Screen cap for reference (see the yellow area). 
![screen shot 2015-02-27 at 6 12 34 pm](https://cloud.githubusercontent.com/assets/64780/6424355/6155d9be-beac-11e4-8910-41a4fb184c03.png)

**Comment by spectralsun** [comment]
Pull #192 looks good except it seems to me that step 1 and 2 are the same, could we get rid of step 1 and the word "Now" on step 2 for simplification? Having 3 messages is kind of overwhelming.

**Comment by d356** [comment]
@spectralsun Thanks for the feedback. Do you mean like this?
![privly-2](https://cloud.githubusercontent.com/assets/10871998/6493235/5bcf6b0c-c287-11e4-9d72-53192064d6e7.PNG)

**Comment by smcgregor** [comment]
Ha, I don't think he did _exactly_ but I was just about to suggest this.

**Comment by spectralsun** [comment]
@d356 I was thinking just remove the top line all together, just have the https link (as the first message) and the message below about copy/paste and the button top open.
@smcgregor thoughts?

**Comment by smcgregor** [comment]
Based on Think-Aloud study results, we must tell the user what to do with the link. So the first message is required.

**Comment by vatsalj** [comment]
Hi privly devs! I was looking into this issue and I feel that the link in a separate `<p>` tag makes it look like an additional step. I made something like this:
![privly snapshot](https://cloud.githubusercontent.com/assets/1089034/6525498/fb90b45c-c42b-11e4-8b41-d5333a3322e4.png)

The advantage of this can be that it maintains the continuity of Step 1 while separating the steps into distinctive paragraphs. Furthermore, the instructions and action-to-be-taken part of 1st step are separated by a horizontal rule as well. Do let me know if this looks like a viable solution to you.

**Comment by smcgregor** [comment]
Looks good to me. @spectralsun, how does it look to you? I think I would make a few changes, but they are more tweaks like rounding the corners, playing with the width of the horizontal rule, etc.

**Comment by vatsalj** [comment]
@smcgregor I'm working on the tweaks right now. I'd like to ask if I should give border radius to all the `p.flash.notice` elements (which includes the connection checking message and the login message as well)?

**Comment by smcgregor** [comment]
Yes. It is hard for me to picture it mentally, but this would probably look better.

**Comment by vatsalj** [comment]
@smcgregor How does this look?
![image](https://cloud.githubusercontent.com/assets/1089034/6530411/b44b1dfa-c456-11e4-9552-cddec3f10aa6.png)

**Comment by smcgregor** [comment]
Looks good.

**Comment by vatsalj** [comment]
Okay, updating the pull request. Is it okay if I amend my commit and force push it? Or do you want me to rebase?

**Comment by smcgregor** [comment]
Why aren't you just adding another commit?

**Comment by vatsalj** [comment]
I wasn't sure of the guidelines. I'll just add a new commit. Thanks! :)

**Comment by smcgregor** [comment]
Fixed by https://github.com/vatsalj/privly-applications/commit/72fc545930b68222d800509c1151a074fe3d82a6
