### ISSUE TITLE
Automagically discover chrome extension ID for testing

### ISSUE THREAD

**Issue by irdan** [privly/privly-applications#171]
From time to time the chrome extension ID is updated.  Currently, the integration tests have the chrome extension ID [hard coded](https://github.com/privly/privly-applications/commit/c8ac0afdd7bd89f41c57196c640bf2658d8a973d#diff-64eee3e287c4a161b21409e68964cf7eR234).  This happens infrequently enough that manually updating the ID works, but it is not ideal.

Since the testing framework is fairly intricate, this issue could be very challenging to debug for the wrong person.  We should find a way to determine the extension ID from the integration testing context, and use it to build the URL in the link above.

**Comment by suryatech** [comment]
@irdan Not sure how the "chrome" variable would be exposed from within the run_all.rb file.

Any thoughts on this?

**Comment by smcgregor** [comment]
We talked about using Selenium to capture it after it is installed, probably from the first-run page since it is supposed to popup every time. This means it would not be a variable in run_all.rb.

@irdan Does that match with what we talked about?

**Comment by smcgregor** [comment]
I think we only need to run this on the first run page, from selenium: `driver.execute_script("return document.location.href")`, since that should give the path containing the ID. The trick is to always select the correct document/window to run this on.

**Comment by smcgregor** [comment]
[Done](https://github.com/privly/privly-applications/blob/685d859fa7fcf49367b986c12aff2cdc2a54acdb/test/selenium/configurations.rb#L51)
