### ISSUE TITLE
WebDriver integration tests fail when running locally

### ISSUE THREAD

**Issue by d356** [privly/privly-applications#203]
Here is my console output: https://gist.github.com/d356/4580cd473f80dea25211

I have the content server running locally and it is handling requests.

test_create_update_destroy(TestNew) fails in a non-deterministic manner.  Yesterday it was not failing for me.  There may be a race condition where it attempts to click too early.

This is after changing
```ruby
Capybara.app_host = "chrome-extension://gipdbddcenpbjpmjblgmogkeblhoaejd"
```
to
```ruby
Capybara.app_host = "chrome-extension://eobjeeellokkdidoihlmnpgjodindnjg" 
```
to reflect the changed extension id.

**Comment by smcgregor** [comment]
Can you link to the branch you ran this on?
