### ISSUE TITLE
Fix page title of extension options

### ISSUE THREAD

**Issue by irdan** [privly/privly-applications#304]
Right now in Chrome the page title of the extension options page is `New Options`.  This should be updated to a more meaningful title such as `Options`.

**Comment by opg7371** [comment]
can you provide a screenshot for what you want to say..i see there is no term as New Options

**Comment by prastut** [comment]
This issue is present on most pages. Added a global fix in PR #360

**Comment by prastut** [comment]
@smcgregor You can close this issue now.
