### ISSUE TITLE
Can't open Privly links in IE

### ISSUE THREAD

**Issue by sakshamsaxena** [privly/privly-applications#323]
So in IE (any version) we have to open the Privly links to see the message. I had never tried this in IE, but being a WP user, I opened a link only to find it loading endlessly. Then I tried to open the same link through IE 11 Desktop, and checked the Debugger. Here's what I found:
![capture](https://cloud.githubusercontent.com/assets/8774516/12865045/0ad5b864-ccc7-11e5-92a8-9d94adc4ef20.PNG)

Thought I should point this out. 
Also, since "Promise" object is found in other scripts as well, I could not even Log In to privly as it could not successfully connect to server.

**Comment by smcgregor** [comment]
Thanks for the report. It looks like we are missing a polyfill. One of the
dangers of most of our devs being on unix derivatives.

**Comment by smcgregor** [comment]
I believe I fixed this issue in #324. I'll update this issue when my PR is deployed to production. Any feedback from the IE side of the internet would be appreciated.

**Comment by sakshamsaxena** [comment]
Apparently, [Promises are supported by default in Edge](http://www.html5rocks.com/en/tutorials/es6/promises/#toc-browser-support). Tested successfully there. It's only IE (all versions) and some older versions of other browsers which require external support. 
Anyways, thanks for the quick response!

**Comment by smcgregor** [comment]
You should be good to go. Please let me know if there are any persistent issues and reopen.
